require: rubocop-rspec

Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Metrics/CyclomaticComplexity:
  Max: 10
Style/FrozenStringLiteralComment:
  Exclude:
    - '**/*' # maybe later, ruby-3 later
RSpec/MultipleExpectations:
  Max: 5
RSpec/ExampleLength:
  Max: 10
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
GlobalVars:
  AllowedVariables:
    - $logger
