:log_level: DEBUG
:webserver:
  :port: 4567
:cricinfo:
  :list_url: 'http://static.cricinfo.com/rss/livescores.xml'
  :match_url: 'https://www.espncricinfo.com/ci/engine/match/'
  :list_cache_expiry: 3600 # 1 hour
  :data_cache_expiry: 120  # 2 mins
